### ISSUE TITLE
Simplify running GHC schedule via Docker

### ISSUE THREAD

**Issue by justb4** [geopython/GeoHealthCheck#106]
This is a proposal to simplify running GHC via Docker(-compose) using plain `cron` i.s.o. `jobber` with the `blacklabelops/cron-cloud` Docker image.

Thoughts are:

- users can use plain `cron` as in non-Docker setups
- can run GHC Docker container also directly via `docker run` (i.s.o. `docker-compose`)
- less dependencies
- in general a more easy(-to-understand) setup
- in the future we may have a native GHC scheduler as we may need a schedule-per-resource

I've tested this setup and will check-in on `dev` branch for review. Hopefully @yjacolin can have a look. I was not involved in the initial GHC Docker design and may have overlooked design decisions. 

I know there are zillion ways to setup (GHC) Docker deployments. We may also need to cater for Postgres setups (i.s.o. `sqlite` via shared Docker Volume).

**Comment by justb4** [comment]
I have used a new branch https://github.com/geopython/GeoHealthCheck/tree/docker_106 for this proposal (i.s.o. `dev`).

**Comment by yjacolin** [comment]
One first quick feedback: it could be good to create an official hub for GWC instead using my name then setup an automatic build either via travis or via docker hub with a panel in the readme file (as for travis build).

**Comment by justb4** [comment]
@yjacolin +1 for GWC Docker Hub.

**Comment by yjacolin** [comment]
About your simplification, here are my comments: the use of cron is not a good practice in a Docker container as it can't use environment variable and have some other drawback but more of all the docker infrastructure is a simple service focused architecture so that's mean that one container should run one service, not more. But of course, one can use differently (and I did it that's way when I learnt docker).

If you want to simplify the docker container (in your mind, that's mean decrease the number of container, right?) you can include the "jobber" container in the main container but it's not seems the best practice as it mixes several services.

> in general a more easy(-to-understand) setup

Reading the docker-compose yaml file you can understand easily that there is 2 "cron" services and the web application. In your changes, if you want to understand the way GHC works, you should read the main dockerfile and understand all "layers". But probably it matters of what you know the best: docker or the GHC source code. I know better docker, I don't know about you :)

> in the future we may have a native GHC scheduler as we may need a schedule-per-resource

I don't understand this and what it implies as I am not involved in the development so I can't have a clear opinion on this :)

> I know there are zillion ways to setup (GHC) Docker deployments. We may also need to cater for Postgres setups (i.s.o. sqlite via shared Docker Volume).

My experience comes from internal project and good practice from our sysadmin and docker experiences. Also, I am not sure that the docker composition should take care of all possibilities but we can easily install sqlite inside GHC container and use of environment variables.

Finally, I have no strong opinion, this is only my comments with my own experience and own good practice. As I am not involved in the project I won't give you a -1 or -1 on this.

If you need some help for docker build with travis, I can help, though.

**Comment by justb4** [comment]
@yjacolin ok, you convinced me :-). Though I solved the cron `env` and `background` problems. But did some more reading (PID 1, reaping zombie problems etc) and the Docker adagium "One Service per Container". Will go ahead with the Jobber-way, trying to fix #105 first.

To clarify: *"in the future we may have a native GHC scheduler as we may need a schedule-per-resource"*:
@tomkralidis  got requirement to schedule health-check-per-Resource, as is usual with uptime checkers. We could run a daemon Docker container based on e.g. [Python Schedule](https://github.com/dbader/schedule) but this is something for the future.

My worry about `sqlite` is that the DB is modified concurrently (UI and cronjobs) via a Docker volume (but also in non-Docker case), plus performance when managing a large number of Resources with long history setting. I figured out that `nginx`<->`gunicorn(ghc)`<->`postgis` (with Jobber) would be a favourable Docker production stack, also since I may be hosting multiple GHC instances. I can provide a `docker-compose` example. I may need to tweak the `Dockerfile` (-scripts) to support PostGIS, e.g. to trigger DB table creation (`paver create`). 

I will open a separate issue for the GHC Docker Hub migration. We can close this issue.
