### ISSUE TITLE
Is WMS 1.3.0 supported?

### ISSUE THREAD

**Issue by josegar74** [geopython/GeoHealthCheck#136]
Is WMS 1.3.0 supported?

I'm trying with this service: http://resource.sgu.se/service/wms/130/berggrund_1M that only supports only 1.3.0 and get the following error response when trying to save the service, there's no additional errors in the console (enabled `DEBUG=True` in `config-site.py`):

```
'NoneType' object has no attribute 'find'
```

I found this issue: https://github.com/geopython/GeoHealthCheck/issues/1, but it's pretty old, not sure if the current version of OWSLib supports 1.3.0?

**Comment by justb4** [comment]
Interesting case! GHC supports WMS 1.3.0 for example for the `WMS GetCapabilities` Probe, see e.g. http://demo.geohealthcheck.org/resource/42 (2 Capabilities Probes activated one for 1.1.1 and one for 1.3.0.). But other WMS Probes need extension (new Probes) for WMS 1.3.0 versions, see  the [GetMapv1* Probes](https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/plugins/probe/wms.py). This is needed since 1.3.0 is very different in e.g. the `REQUEST_TEMPLATE` (CRS i.s.o. SRS etc). 

Though you can always add your URL as a generic `Web Address URL` `Resource`. and paste a Caps URL or GetMap URL and assign from `Checks Avail` `Checks`  for strings like `Title` or Content-Type in response doc, but that would be temporary.

I see that [OWSLib only supports WMS 1.1.1](https://github.com/geopython/OWSLib/blob/master/owslib/wms.py), @tomkralidis can fill in. The problem you are facing is that on adding a `Resource` the URL is first accessed using (OWSLib) `GetCapabilities` v1.1.1, which fails in your case as only 1.3.0 is supported, and your `Resource` is not added. Most WMSs supporting 1.3.0 also support 1.1.0, it may even be required by the OGC WMS standard, but you are not helped with that. 

A solution within GHC is to skip this initial check, as a `* Capabilities` Probe is always assigned by default and you can then change the WMS version to 1.3.0 (all `REQUEST_TEMPLATE`-based Probes use Python `requests` package, not OWSLib). But for detailed WMS 1.3.0 Probes the existing  [GetMapv1* Probes](https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/plugins/probe/wms.py) need to be extended. But these use OWSLib...

**Comment by josegar74** [comment]
WMS 1.3.0 seem supported, but when creating the resource no version is set and assigns 1.1.1 (although later can be changed in the edit form to use 1.3.0). 

As the provided service only supports 1.3.0 ,doesn't allow to create the service due to the failure checking the GetCapabilities response for 1.1.1:

Related code:

https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/app.py#L475
https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/healthcheck.py#L81
https://github.com/geopython/OWSLib/blob/master/owslib/wms.py#L46-L55

I see 2 possible options, but not sure which can be preferred:

1) Add in the create resource form a field to select the version.

2) Add fallback mechanism so if fails with 1.1.1 tries 1.3.0.

**Comment by tomkralidis** [comment]
OWSLib supports 1.1.1 by default (this should be changed to 1.3.0 at some point) and does not do version negotiation. I think we should update GHC to have OWSLib use 1.3.0 and if that fails fall back to 1.1.1. Thoughts?

**Comment by justb4** [comment]
We can make the initial check less strict, when adding the `Resource` (which happens [here](https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/app.py#L475)). i.e. issue a warning but still add the Resource, since:

* the service may be currently down or not compliant. Adding it allows a user to reconfigure/tweak the service endpoint.
* it complicates things, custom code is needed which basically already happens in the Probes, we may get more cases, like found with WCS
* more independence from `OWSLib` versions
* the user can always construct `Probes`,like free-form GET/POST  which can still work with the Resource
* ` Probes` have a more detailed error-reporting, including email
* we need to keep form fields/extra information with the `Probe` for version info

And add this:

* Allow users to modify the URL after adding, sometimes there is a typo or a URL-rename

This is also the quickest fix.  The [sniff_test_resource](https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/healthcheck.py#L66) is mainly handy to get the `Resource` title, but all checks are better done via `Probes`.

**Comment by hannesaddec** [comment]
Would be both be feasible..
In case version is left as default, try 1.3

**Comment by justb4** [comment]
Strange thing here is that service responds with 1.3.0 caps even if 1.1.1 is specified:
http://resource.sgu.se/service/wms/130/berggrund_1M?service=WMS&request=GetCapabilities&version=1.1.1 but OWSLib note failure on parsing I guess.

**Comment by tomkralidis** [comment]
We can implement version negotiation to cover 1.3.0 then 1.1.1 support ([example](https://github.com/cga-harvard/HHypermap/blob/master/hypermap/aggregator/utils.py#L415-L426))

**Comment by justb4** [comment]
@tomkralidis tried that, works fine, will commit together 

* with some fixes for auto-removing Probes specific to v1.1.1 that do not initialize
* adding the `Resource` even if initial `sniffing` failed, as also an initial `Run` is added (see above)

To be added to `dev` branch..

**Comment by justb4** [comment]
Ok, could now add http://resource.sgu.se/service/wms/130/berggrund_1M on http://dev.geohealthcheck.org (removed it as well, so you can try). After adding, in Edit mode change the WMS version for the `WMS GetCaps Probe` from 1.1.1 to 1.3.0.

**Comment by josegar74** [comment]
You're great @justb4, thanks a lot!

**Comment by justb4** [comment]
@josegar74  So we can close this one?

**Comment by josegar74** [comment]
@justb4 yes, thanks for the quick fix.
