### ISSUE TITLE
GHC - Docker - SSL: Unknown_Protocol

### ISSUE THREAD

**Issue by StephanZaat** [geopython/GeoHealthCheck#158]
I'm trying to get GHC to work and use this URL (which works fine in QGIS and via curl/browser):
https://map.data.amsterdam.nl/maps/bag

When I enter it in GHC and click test it fails with the following details.
This is running as Docker with version: Powered by GeoHealthCheck 0.3-dev.

```
{
  "end_time": "2017-09-06T07:01:07Z",
  "message": "Request Err: SSLError HTTPSConnectionPool(host='map.data.amsterdam.nl', port=443): Max retries exceeded with url: /maps/bag?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetCapabilities (Caused by SSLError(SSLError(1, u'[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:661)'),))",
  "probes": [
    {
      "checks": [],
      "class": "GeoHealthCheck.plugins.probe.owsgetcaps.WmsGetCaps",
      "message": "Request Err: SSLError HTTPSConnectionPool(host='map.data.amsterdam.nl', port=443): Max retries exceeded with url: /maps/bag?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetCapabilities (Caused by SSLError(SSLError(1, u'[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:661)'),))",
      "name": "WMS GetCapabilities",
      "probe_id": 2,
      "response_time": "0.22323",
      "success": false
    }
  ],
  "report_version": "1",
  "resource_id": 1,
  "resource_title": "BAG PROD",
  "resource_type": "OGC:WMS",
  "response_time": "0.25358",
  "start_time": "2017-09-06T07:01:06Z",
  "success": false,
  "url": "https://map.data.amsterdam.nl/maps/bag"
}
```

If I do a general URL with https it works. When I use another WMS (both http and https) it works. 
It might be due to the way we've set up our TLS / SSL, but other apps seem to have no issues.
Any ideas?

Many thanks again for the great project. Looking forward to bringing it into production!

**Comment by justb4** [comment]
Thanks. I think this is not related to your server's SSL setup, its report is A+:
https://www.ssllabs.com/ssltest/analyze.html?d=map.data.amsterdam.nl&hideResults=on

So most likely the problem is in the client, more specific the SSL-client used.
Dived into this further by registering https://map.data.amsterdam.nl/maps/bag on several GHC instances on different OSs/versions and googling for the error. On recent OS-versions like Ubuntu 16.04 also using GHC Docker version `GeoHealthCheck 0.3-dev` and on Mac OSX 10.11.6 with Homebrew Python 2.7: no problem. Debian (wheezy 2013): failed, though with different error. Similar errors occur with older versions of the OS OpenSSL lib, see 
[this search](https://www.google.nl/search?q=SSLError+SSL+%22UNKNOWN_PROTOCOL%22++python+requests&oq=SSLError+SSL+%22UNKNOWN_PROTOCOL%22++python+requests&gs_l=psy-ab.3..35i39k1.16387.28346.0.28931.4.4.0.0.0.0.139.330.3j1.4.0....0...1.1.64.psy-ab..0.3.244.16k4ccYD4rI) .

Another possibility is that your GHC instance is using a proxy, and that internal HTTPs requests are somehow not routed, as other HTTPS URLs work, though still it may be a subtle SSL negotiation error w.r.t. TLS versions (see search). Even if you use the same GHC Docker image version, networking requests may be passed via Docker and underlying OS libs IMO. 

So first we need to determine what your OS environment/versions are in which you deploy GHC with Docker.
In Linux the command `openssl version` gives the OpenSSL version.

**Comment by StephanZaat** [comment]
Thanks again for the super fast response.

What's interesting is that the server the GHC docker runs on also has issues with curl:
```
user@server:~# curl -v "https://map.data.amsterdam.nl/maps/bag"
*   Trying 185.3.210.48...
* Connected to map.data.amsterdam.nl (185.3.210.48) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 692 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* gnutls_handshake() failed: An unexpected TLS packet was received.
* Closing connection 0
curl: (35) gnutls_handshake() failed: An unexpected TLS packet was received.
```

```
user@server:~# curl -V
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
```

```
root@admin:~# docker -v
Docker version 17.05.0-ce, build 89658be

OpenSSL version:
OpenSSL 1.0.2g  1 Mar 2016
```

I have other servers which don't seem to have these issues with all the same versions. Locally it also works fine. Like you mention, this seems to be a network issue. I will research further and will post my results.

**Comment by StephanZaat** [comment]
This seems to be a very specific issue with this server. I will redeploy it at some time. It works fine on another server. Thanks for all the support!
