### ISSUE TITLE
docker-compose.postgis.yml misses image entries

### ISSUE THREAD

**Issue by MarcoDuiker** [geopython/GeoHealthCheck#180]
In docker-compose.postgis.yml
the line 
>` image: geopython/geohealthcheck:latest`

is missing under the services:
- `geohealthcheck`
- `geohealthcheck-cron-daily`
- `geohealthcheck-cron-hourly`

Adding the mentioned line allows the services to run.

**Comment by justb4** [comment]
Ha, this is on purpose, in order to reuse `docker-compose.yml`, see also the README, run via:

```
docker-compose -f docker-compose.yml -f docker-compose.postgis.yml up [-d]
```
But you are free to merge them all in a single compose file, and maybe that is clearer. In an upcoming version, see PR #175, we will do away with the `cron/Jobber` and schedule per resource within Python itself, so then we can make `docker-compose.postgis.yml` self-contained.

**Comment by MarcoDuiker** [comment]
Ah sorry for the noise.

I didn't read the docs well enough: https://github.com/geopython/GeoHealthCheck/blob/master/docker/README.md
