### ISSUE TITLE
Add, info and edit button not visible in edit_ressource

### ISSUE THREAD

**Issue by Gabriel-Desharnais** [geopython/GeoHealthCheck#204]
![screenshot_20180528_135049](https://user-images.githubusercontent.com/17755977/40625605-8be97ef2-6281-11e8-9e09-caf23ba98784.png)
I can't add or edit any probes since they overflow from a div that doesn't show overflow. I'll work on a solution and there should be a pull request soon.

**Comment by justb4** [comment]
Good you are looking into this! I've also noticed cases that edit buttons disappear on the right. The buttons *were* there though: they disappeared because of a horizontal scrollbar after excess text. Scrolling that scrollbar brought the buttons back in sight. But this still will be annoying to the user.

I will review your fix #205. Hopefully that will get the buttons in place!

**Comment by Gabriel-Desharnais** [comment]
I've tested a fresh build after the merge and it seems to have solved the problem
