### ISSUE TITLE
which requests do probes fire

### ISSUE THREAD

**Issue by deRightDirection** [geopython/GeoHealthCheck#324]
I configured several probes on wms/wfs-services and i get errors which can't directly solve.
Because for my understanding it would be very usefull to know which url's the probes are really requesting.

For example the WMS Drilldown gives continuously an error message. But what does it do exactly?
I would try to use the same url's as GHC uses to do a check on the service as well.

Now I feel that we have false negatives in the results of GHC.

How can I do cross-checks of the results coming from GHC?

**Comment by justb4** [comment]
Good question, no complete answer. For now the best is to check logfiles on your WMS/WFS server for incoming requests.
Think this would be a useful feature, though bit tricky because of security implications for authenticated Resources.
Can you open a "new feature" issue for this?

As for "WMS Drilldown": this Probe is a bit experimental. What it does is "crawl" from the Capabilities doc and determine the Layer list, do a request on a random Layer using a random published Image Formats. Most WMS-es publish Image Formats and or Projections  that in practice are not supported, leading to errors. As there is some randomness in picking Formats and other options, the failures may not be the same each time, or Probe may even pass.

For WMS it is best to use the `'WMS GetMap WMS v1.1.1. operation on ALL Layers'` `Probe` on a very small bounding box. This gives the most confidence that all Layers are operational.

**Comment by justb4** [comment]
This question is answered. No feedback, closing.
