### ISSUE TITLE
Load time of the main page is slowed with a lot of registers in table 'run'

### ISSUE THREAD

**Issue by marcelo-alejo** [geopython/GeoHealthCheck#43]
## User Story

As a user, developer
I have more than 1 million records in the table 'run' amount , and the charging time of the main page takes too long to load.
## Proposal

Create an option to display the 'Status' and 'Response times' from a certain time, such as 1, 2, 3 ... months ago.
## Discussion
- I tried limiting the query using a certain date, but the page load continue to slow.
- I'm testing the use of a temporary table for the home page to get 'Status' and 'Response time' of each resource , this table may be updated from time to time.
- Or any suggestions to improve the loading time of the page with that amount of records.

**Comment by Djalmar** [comment]
I'm having kinda same problems, any sugestions where it can be the problem with the slow response ?

**Comment by justb4** [comment]
IMHO these problems arise since all statistics are calculated "on the fly", on page-loading: the DB is queried for all ``Runs`` for all ``Resources``. If their numbers (records/rows) increase so would be all stats calculations.

While calculating the stats from their raw data (``Runs``) is the most flexible and reliable, clearly this would not scale when numbers grow. Caching could be one answer to this dilemma. I'll try to sketch an idea:

* add a new Model class "Stats" (or "RunStats") and corresponding DB table
* each row in Stats will keep statistics for a single Resource: number of runs, min/max response time, average resp time, FK first,last run etc. Possibly  as a JSON doc in a column as new stat types may evolve.
* on each ``run_test_resource()`` both the Run and Stats tables would be updated
* on page load, only the "Stats" table would be queried, "get all"
* in case that ``Stats`` gets of out of sync it  may always be regenerated using a ``Paver`` command

For keeping a "cumulative average" there is a formula such that not all values are required for average calculation. Used this before for keeping stats on average air quality, something like:

```
    # M = M + (x-M)/n
    # Here M is the (cumulative moving) average, x is the new value in the
    # sequence, n is the count of values. Using floats as not to loose precision.
    def moving_average(self, M, x, n):
        return float(M) + (float(x) - float(M)) / float(n)
```

Other interesting variants are what i think is called "running average", e.g. the last 24 hour average. Like said: when using a ``Stats`` table we need to be flexible (JSON attribute or go for NoSQL...).

**Comment by tomkralidis** [comment]
+1 for a `Stats` or `Metrics` model which is updated on a given `Run`, as well as the ability to regenerate via Paver.  Good suggestion @justb4!

**Comment by melizabethq** [comment]
Hi,
I have had the same problem, and well I would like to know if in the next version will be made correction of this problem? And to know if any of the solutions proposed by marcelo-alejo and justb4, could be taken as a solution. First of all, Thanks.
Regards

**Comment by justb4** [comment]
I'm in favour of keeping the spirit of this issue preferably in a new enhancement issue for a ``Stats``/``Metrics`` model  (see above) and in shorter term resolving issue #76. Also for "big" installations a Postgres backend may be a better option than SQLite, now enabled via issue #73.
