### ISSUE TITLE
Probes/checks run once and never repeat

### ISSUE THREAD

**Issue by Myrdrahl** [geopython/GeoHealthCheck#437]
I'm sorry but I cannot for the life of me understand what's going on and there are nothing in the logs indicating anything wrong either. Maybe I'm missing something, but I've read the documentation here and the the one that is avaliable through the "help" in the running solution. 

![ghc](https://user-images.githubusercontent.com/16894766/190394867-827c271b-681b-415c-8c47-6030e46ee531.jpg)

The sqlite database are being populated, as new resources are being added. So the only run that's being performed, seem to be when the resource is added and nothing happens after that. Pressing the "test now" from the resouce, shows this:
![bilde](https://user-images.githubusercontent.com/16894766/190395381-b859c632-e1f8-4cd7-93c3-815d6b514883.png)

Indicating everything was fine, however, the data for the resource is not being updated, no statistics are updated, no reaction or idication at all, that a test was actually run at all. 

I'm very confused by all of this, but maybe I've missed something vital despite me reading the documentation over and over. If anyone have any clue to what I'm missing, I'd be very thankful!

**Comment by justb4** [comment]
Hmm, looks a bit like this issue:
https://github.com/geopython/GeoHealthCheck/issues/303. We did not want to change that default, since then other problems may arise. 
So set `GHC_RUNNER_IN_WEBAPP` to True in your config. If you use the `docker run` command you may use the `-e` option.

GHC needs a 'Runner'. This can be a separate Docker Container (preferred) or in the Docker Container running the webapp (as you do). For just local testing it is ok, but for production not recommended.
Best is to use `docker compose` as in this example:
https://github.com/geopython/GeoHealthCheck/blob/master/docker/compose/docker-compose.yml

**Comment by Myrdrahl** [comment]
Thanks again! Yes, this did infact fix it! I completely missed that this would be needed, for some reason.
