### ISSUE TITLE
Multiple "fixed" emails being sent out for one resource

### ISSUE THREAD

**Issue by archaeogeek** [geopython/GeoHealthCheck#78]
Hi,

I'm running GeoHealthCheck with postgresql as the back end database. I've got one resource which is occasionally corrected reported as unavailable, but is now fixed. GeoHealthCheck is sending out multiple "fixed" emails, one every hour for this one resource. When I look in the "run" table in the database I can see the entry for the failure, and then the subsequent ones saying it's running OK, but I'm not sure why it's sending so many "fixed" emails out. This only happens for one resource, all the others are behaving as expected. 

The other odd thing is that when I look at the failures, the most recent one was a 503 service unavailable error, but all the "fixed" emails say the following (this one was sent at 11AM):

Details:

Date: 2016-12-30T01:00:32Z

Message: <urlopen error [Errno 110] Connection timed out>

I'm not sure this is a repeatable issue, but I was wondering if you have any ideas how I might debug the problem and hopefully solve?

Thanks!

**Comment by justb4** [comment]
As your installment is using Postgresql with notifications, I suspect that this odd behaviour stems from a difference with Sqlite. At least I've never seen this in the combo GHC+Sqlite. In order to determine whether a notification should be sent, the code in both [models.py](../blob/master/GeoHealthCheck/models.py) and [notifications.py](../blob/master/GeoHealthCheck/notifications.py) use quite some boolean comparisons, some implicit like ``if last_run_success`` etc. It could be that the mapping of database columns is messing up these comparisons. But this is theory, the proof is in the pudding, i.e. debugging and stepping through the comparisons. 

To debug I use an IDE allowing stepwise debug, IntelliJ IDEA, but PyCharm or other IDEs like Eclipse can do this as well. The program to debug is ``models.py run``. Attached is my IntelliJ config. I have to setup with Postgresql to test, but maybe you are able to help us here. Start with a breakpoint at [models.py L255](../blob/master/GeoHealthCheck/models.py#L255). This could also be a starting point for 503 errors.

![debug-ghc](https://cloud.githubusercontent.com/assets/582630/21718472/0033a7a0-d418-11e6-9d28-569ff1c6f7b1.png)

**Comment by justb4** [comment]
Debugged with Postgres backend: I cannot reproduce multiple ``Fixed`` messages after a ``Failing``. The mapping to Postgres also looks ok with both Booleans in the column and in Python. Also strange that is is just one resource. Maybe something with time(zones) such that the False``lastrun`` remains last always, check the  ``checked_datetime`` field?

**Comment by archaeogeek** [comment]
Sorry, it looks like I actually have a different problem to what I originally thought. While I am still getting emails from this one resource, and the GeoHealthCheck site is running, I don't have any entries for any resources later than the 30th of December 2016. Even if I do a manual check I'm not seeing it recorded in the table. The latest entry in the run table is the one for the urlopen error [Errno 110] Connection timed out error that I mentioned in my original issue and that's being mentioned in the emails. I will close this and do some serious debugging to see what on earth is going on!

**Comment by archaeogeek** [comment]
For what it's worth, this is a hangover from switching from sqlite to postgresql and trying to preserve the original tables, specifically the run history. When I run models.py I can see that it's triggering a primary key error, where it's trying to add records with identifiers that duplicate those in the table already. I think the dirty hack is to run models.py until it increments the identifier high enough to start adding new records. I recall having a similar problem with adding new sources to the source table- it failed a couple of times until the identifier was unique again. 

So it's not a bug as such, but it might be worth including some guidance in the documentation on how best to switch from one back-end to another preserving the existing tables, unless the best advice is just to drop them and start from scratch...

**Comment by justb4** [comment]
Aha, yes for now starting from scratch or some custom DB dump/restore would be the best option. The resolution to issue #20 may later be a solution. We are planning a codesprint in feb: https://wiki.osgeo.org/wiki/Daytona_Beach_Code_Sprint_2017. Having an (REST) API as part of rearchitecture is in view. Ask Tom for specifics if you want to be involved. You can use [GHC Gitter](https://gitter.im/geopython/GeoHealthCheck) for discussion.
